[package]
name = "puzzle10"
version = "0.1.0"
authors = ["Philip Chimento <philip.chimento@gmail.com>"]
edition = "2018"

[[bin]]
name = "puzzle10"
path = "puzzle10.rs"

[dependencies]
itertools = "0.9.0"
