[package]
name = "puzzle20"
version = "0.1.0"
authors = ["Philip Chimento <philip.chimento@gmail.com>"]
edition = "2018"

[[bin]]
name = "puzzle20"
path = "puzzle20.rs"

[dependencies]
bit_reverse = "0.1.8"
itertools = "0.9.0"
ndarray = "0.14.0"
scan_fmt = "0.2.5"
